services:
  _defaults:
    public: true

  democqrshooksusage.domain.reviewer.command_handler.toggle_is_allowed_to_review_handler:
    class: 'DemoCQRSHooksUsage\Domain\Reviewer\CommandHandler\ToggleIsAllowedToReviewHandler'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
    tags:
      - name: tactician.handler
        command: 'DemoCQRSHooksUsage\Domain\Reviewer\Command\ToggleIsAllowedToReviewCommand'
